### ISSUE TITLE
virt-sysprep: base image missing `perl` binary for `edit` customization

### ISSUE THREAD

**Issue by jbpratt** [kubevirt/kubevirt-tekton-tasks#113]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`virt-sysprep` `ClusterTask` fails if an `edit` command is passed in. `virt-sysprep` and `virt-customize` allow for non-interactive editing of a file like so and requires `perl` to be installed:
```
 edit /some/file:s/^OPT=.*/OPT=ok/
```

https://github.com/rwmjones/guestfs-tools/blob/3a498512f58bc431db490e96cdb712b19389bda4/customize/perl_edit-c.c#L42
https://github.com/rwmjones/guestfs-tools/blob/3a498512f58bc431db490e96cdb712b19389bda4/customize/perl_edit.ml#L22-L30

Should the `perl` binary be included in `kubevirt/libguestfs-tools`? I can't seem to find where this image lives.

https://github.com/kubevirt/kubevirt-tekton-tasks/blob/07b8ea374f9db413dc48c0c1aac4b69dae6aa609/modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile#L19

**What you expected to happen**:
success :)

**How to reproduce it (as minimally and precisely as possible)**:
```
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kmi-pipeline
spec:
  tasks:
    - name: create-datavolume-from-manifest
      taskRef:
        kind: ClusterTask
        name: create-datavolume-from-manifest
      params:
        - name: waitForSuccess
          value: 'true'
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: fedora-35-
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
                volumeMode: Filesystem
              source:
                http:
                  url: https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-35-1.2.x86_64.qcow2

    - name: disk-virt-sysprep
      params:
        - name: pvc
          value: "$(tasks.create-datavolume-from-manifest.results.name)"
        - name: sysprepCommands
          value: |
            run-command dnf -y --best upgrade --exclude=kernel*
            edit /etc/selinux/config:s/^SELINUX=enforcing/SELINUX=permissive/
            install vim,tmux
            run-command dnf clean all
            delete /var/cache/dnf
        - name: additionalOptions
          value: "--network"
      taskRef:
        kind: ClusterTask
        name: disk-virt-sysprep
      runAfter:
        - create-datavolume-from-manifest
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kmi-pipelinerun-
spec:
  pipelineRef:
    name: kmi-pipeline
  serviceAccountNames:
    - taskName: create-datavolume-from-manifest
      serviceAccountName: create-datavolume-from-manifest-task
```

```
...
[disk-virt-sysprep : run-virt-sysprep] [   5.2] Performing "utmp" ...
[disk-virt-sysprep : run-virt-sysprep] [   5.2] Performing "yum-uuid" ...
[disk-virt-sysprep : run-virt-sysprep] [   5.2] Performing "customize" ...
[disk-virt-sysprep : run-virt-sysprep] [   5.2] Setting a random seed
[disk-virt-sysprep : run-virt-sysprep] [   5.2] Setting the machine ID in /etc/machine-id
[disk-virt-sysprep : run-virt-sysprep] [   5.2] Running: dnf -y --best upgrade --exclude=kernel*
[disk-virt-sysprep : run-virt-sysprep] [  50.0] Editing: /etc/selinux/config
[disk-virt-sysprep : run-virt-sysprep] sh: perl: command not found
[disk-virt-sysprep : run-virt-sysprep] virt-sysprep: error: failure: rm: /var/run/utmp: No such file or directory
[disk-virt-sysprep : run-virt-sysprep]
[disk-virt-sysprep : run-virt-sysprep] If reporting bugs, run virt-sysprep with debugging enabled and include the
[disk-virt-sysprep : run-virt-sysprep] complete output:
[disk-virt-sysprep : run-virt-sysprep]
[disk-virt-sysprep : run-virt-sysprep]   virt-sysprep -v -x [...]

failed to get logs for task disk-virt-sysprep : container step-run-virt-sysprep has failed  : [{"key":"StartedAt","value":"2022-02-18T20:54:20.324Z","type":3}]
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.49.0", GitCommit:"f8160a0b5eac2acafab74fd7916bfcaf0c39a6a3", GitTreeState:"clean", BuildDate:"2022-01-11T17:37:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platfo
rm:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.46.0-dirty", GitCommit:"3ebb0a03fde639ea9afb5ee83ac7ac72dbeb4a9d", GitTreeState:"dirty", BuildDate:"2021-10-08T21:39:28Z", GoVersion:"go1.16.6", Compiler:"gc",
Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"archive", BuildDate:"2022-01-27T18:26:18Z", GoVersion:"go1.17.
6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9"
, Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- tekton-pipelines version:
```
Client version: 0.21.0
Pipeline version: v0.33.0
```

- kubevirt-tekton-tasks version: `v0.4.0`
- CDI version if applicable: `v1.42.1`
