### ISSUE TITLE
Allow Kubernetes's built-in ssh-auth secret type

### ISSUE THREAD

**Issue by fzdarsky** [kubevirt/kubevirt-tekton-tasks#52]
KubeVirt Tekton Tasks currently requires SSH credentials to be stored as an "Opaque" secret type with its own, project-specific fields. This means one cannot reuse SSH credentials from other contexts.

How about defaulting to (or at least allowing) Kubernetes's built-in "kubernetes.io/ssh-auth" type [1], meaning to allow secrets to be specified as:

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-ssh-auth
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    LS0tLS1CRUdJTiBPUEVOU1NI ...
  ssh-publickey: |
    U0bVBRUk82dUs5Y2ZWRWhDZU ...
```

[1] https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets
